### ISSUE TITLE
Support 'let' binding syntax.

### ISSUE THREAD

**Issue by bradleymackey** [delphinus/vim-firestore#10]
`*.rules` files now allow for local variable declarations via `let` bindings in functions. This is currently recognised as a syntax error.

**Comment by delphinus** [comment]
https://firebase.google.com/docs/rules/rules-language#function

OK, I will add declarations for this.

**Comment by delphinus** [comment]
@bradleymackey I added it. Thx for good catch!

**Comment by bradleymackey** [comment]
Thanks for the great repo!
