### ISSUE TITLE
Collection Group rules are always highlighted

### ISSUE THREAD

**Issue by tanabee** [delphinus/vim-firestore#13]
Collection Group rules are always highlighted. An example is shown below.

```
match /{path=**}/collection/doc {
}
```

screenshot
<img width="874" alt="スクリーンショット 2020-11-10 16 05 41" src="https://user-images.githubusercontent.com/2603644/98641139-a5cd4500-236e-11eb-9f0d-64afbcf1e99f.png">

Is there any solution?

**Comment by delphinus** [comment]
Hmm... seems now any name is allowed for recursive wildcards?

https://firebase.google.com/docs/firestore/security/rules-structure#recursive_wildcards

Anyway, good catch! fixed.

<img width="249" alt="スクリーンショット 0002-11-10 19 39 34" src="https://user-images.githubusercontent.com/1239245/98663787-dde38080-238c-11eb-9566-ccbf07d8339b.png">

**Comment by tanabee** [comment]
Thank you so much!
